version: '3.8'
services:

  app:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bank-app
    working_dir: /var/www/app
    ports: 
      - 8080:80 
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
volumes:
  node_modules:

  # nginx: 
  #   image: nginx:latest
  #   container_name: bank-nginx
  #   working_dir: /var/www/app
  #   volumes:
  #     - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
  #   ports:
  #     - 8080:80
